config/routes.rb
Rails.application.routes.draw do
  mount Judge::Engine => '/judge'

  get 'home' => 'home#index', as: 'home'

  # employee
  get 'employees' => 'users#employees', as: 'employees'
  get 'employees/:id' => 'users#show_employee', as: 'show_employee'

  #managers
  get 'managers' => 'users#managers', as: 'managers'
  get 'managers/:id' => 'users#show_manager', as: 'show_manager'


  #owners
  get 'owners' => 'users#owners', as: 'owners'
  get 'owners/:id' => 'users#show_owner', as: 'show_owner'


  # employee options
  get 'employees/:employee_id/new_client' => 'clients#new', as: 'employee_new_client'
  get 'employees/:employee_id/client/:id' => 'clients#show', as: 'show_through_employee'

  # root 'users#index'

  # logging and logging out
  root 'sessions#new'
  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create', as: 'check_login'
  get 'logout' => 'sessions#destroy', as: 'logout'

  # the various users
  resources :users

  # clients and their transactions
  resources :clients do
    resources :transactions do
      post 'pay' => 'transactions#pay', as: 'pay'
    end
  end

  # password_related
  get 'users/:id/change_password' => 'users#change_password', as: 'change_password'
  patch 'users/:id/change_password' => 'users#update_password'
  put 'users/:id/change_password' => 'users#update_password'

  post ':id/fees/new' => 'fees#create', as:'new_fee'

  get 'reports/services_report' => 'reports#services_report', as: "reports_services_report"

  get 'clients/:id/transactions/:transaction_id/edit/:provisional_receipts_id' => 'transactions#edit_for_modal', as: "edit_modal_provisional_receipts"
  patch 'clients/:id/transactions/:transaction_id/edit/:provisional_receipt_id' => 'provisional_receipts#update', as: "edit_provisional_receipts"

  get 'reports/accounts_receivable'

  get 'reports/employees_report'

  get 'reports/transactions_report'

  resources :reports

  resources :transactions, except: :new

  resources :fees

  resources :services

  resources :provisional_receipts, except: [:new, :create]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :clients, :dependent => :restrict_with_error
  has_many :transactions, through: :clients

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, confirmation: true
  validates :password, length: { minimum: 8 }, presence: true
  validates :email, presence: true, email: true

  attr_accessor :password
  before_save :encrypt_password

  attr_accessor :password

  def encrypt_password
    return false unless @password.present?
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(@password, password_salt)
  end

  def self.authenticate(email, password)
    user = find_by(email: email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    end
  end

  def update_info(params)
    nice = true
    params.each do |key, value|
      nice &&= update_column key, value
    end
    nice
  end

  def get_filtered_total_sales(startdate, enddate)
    transactions.where(:created_at => startdate..enddate).inject(0) {|sum, cost| sum + cost.total_balance}
  end

  def name
    [first_name, last_name].join ' '
  end

  def total_sales
    clients.inject(0) {|sum, cost| sum + cost.total_balance_of_transaction}
  end

  def client_count
    clients.size
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy, :change_password, :update_password, :clients]
  load_and_authorize_resource
  add_breadcrumb "Home", :root_path

  def index
  end

  def employees
    add_breadcrumb "Employees", employees_path
    @employees = get_employees
  end

  def managers
    add_breadcrumb "Managers", managers_path
    @managers = get_managers
  end

  def owners
    add_breadcrumb "Owners", owners_path
    @owners = get_owners
  end

  def show_employee
    @employee = User.find(params[:id])
    @clients = @employee.clients

    add_breadcrumb "Employees", employees_path
    add_breadcrumb @employee.email, show_employee_path
  end

  def show_manager
    @manager = User.find(params[:id])

    add_breadcrumb "Managers", managers_path
    add_breadcrumb @manager.email, show_manager_path
  end

  def show_owner
    @owner = User.find(params[:id])

    add_breadcrumb "Owner", owners_path
    add_breadcrumb @owner.email, show_owner_path
  end

  def show
  end

  def new
    add_breadcrumb "Employees", employees_path
    add_breadcrumb "New User", new_user_path
    @user = User.new
  end

  def edit
    add_breadcrumb "Employees", employees_path
    add_breadcrumb "Edit " + @user.email
  end

  def update
    if @user.update_info edit_user_params
      flash[:success] = 'Profile successfully updated.'
      if @user.role == 'employee'
        redirect_to show_employee_path(@user)
      elsif @user.role == 'manager'
        redirect_to show_manager_path(@user)
      elsif @user.role == 'owner'
        redirect_to show_owner_path(@user)
      end
    else
      flash[:error] = 'Profile WAS NOT updated.'
      render :edit
    end
  end

  def destroy
    role = @user.role
    @user.destroy
    if @user.destroyed?
      flash[:success] = 'User successfully deleted.'
    else
      flash[:error] = 'User WAS NOT deleted. This user may still have clients.'
    end
    if role == 'employee'
      redirect_to show_employee_path(@user)
    elsif role == 'manager'
      redirect_to show_manager_path(@user)
    elsif role == 'owner'
      redirect_to show_owner_path(@user)
    end
  end

  def create
    add_breadcrumb "New User", new_user_path
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User successfully created.'
      if @user.role == 'employee'
        redirect_to show_employee_path(@user)
      elsif @user.role == 'manager'
        redirect_to show_manager_path(@user)
      elsif @user.role == 'owner'
        redirect_to show_owner_path(@user)
      end
    else
      flash[:error] = 'User WAS NOT created.'
      render :new
    end
  end

  def change_password
    add_breadcrumb "Employees", employees_path
    add_breadcrumb "Change Password of " + @user.email , change_password_path
  end

  def update_password
    if User.authenticate(@user.email, params[:user][:old_password]) || can?(:manage, User)
      if @user.update(user_params)
        flash[:success] = 'Successfully updated password.'
        if @user.role == 'employee'
          redirect_to show_employee_path(@user)
        elsif @user.role == 'manager'
          redirect_to show_manager_path(@user)
        elsif @user.role == 'owner'
          redirect_to show_owner_path(@user)
        end
      else
        flash[:error] = 'Something went wrong.'
        render :change_password
      end
    else
      flash[:error] = 'Wrong Password'
      render :change_password
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :role, :password, :password_confirmation)
  end

  def edit_user_params
    params.require(:user).permit(:last_name, :first_name, :email, :role)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/change_password.html.erb
<h1 class="text-capitalize"> Change Password </h1>
<hr>

<%= form_for @user, url: {action: 'update_password'} do |f| %>
  <% if @user.errors.any? %>
    <%= render "shared/error_messages", locals: {form_model: @user} %>
  <% end %>

    <div class="col-sm-5 col-md-8" id="panel">
  <div class="form-group">
    <% unless can? :manage, User %>
      <%= f.label :old_password , class:"control-label", for:"inputOld" %>
      <%= f.password_field :old_password, class: "form-control", id:"inputOld" %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'New Password', class:"control-label", for:"inputNew" %>
    <%= f.password_field :password, class: "form-control", id: "inputNew" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'New Password Confirm' , class:"control-label", for:"inputConfirm" %>
    <%= f.password_field :password_confirmation, class: "form-control", id:"inputConfirm" %>
  </div>

  <div class="actions col-md-6 pull-right">
    <%= f.submit "Update User", class: "btn btn-primary btn-md btn-block" %>
  </div>
</div>
<% end %>

app/views/users/clients.html.erb
<% @clients.each do |client| %>
    <div class="container">
      <p>
        <%= client.company_name %>
      </p>
      <p>
        Owner: <%= client.owner %>
      </p>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1> Edit User  </h1>
<hr>
<%= form_for @user, url: {action: 'update'} do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <%= render partial: "shared/error_messages", locals: {form_model: @user} %>
</div>
<% end %>
  <div class="col-sm-5 col-md-8" id="panel">
<div class="form-group">
  <%= f.label :first_name, class:"control-label", for:"inputFirstName" %>
  <%= f.text_field :first_name, class: "form-control", type: "text", pattern: "^[A-Za-z ]+$", required: "required", id:"inputFirstName", placeholder: "First Name goes here..."  %>
</div>
<div class="form-group">
  <%= f.label :last_name, class:"control-label", for:"inputLastName" %>
  <%= f.text_field :last_name, class: "form-control", type: "text", pattern: "^[A-Za-z ]+$", required: "required", id:"inputLastName", placeholder: "Last Name goes here..." %>
</div>
<div class="form-group">
  <%= f.label :email, class:"control-label", for:"inputEmail" %>
  <%= f.text_field :email, class: "form-control", type: "email", required: "required", id:"inputEmail", placeholder: "sample@gmail.com, example@yahoo.com" %>
</div>

  <% if can? :manage, User %>
    <h5>Role:</h5>
  <%= f.radio_button :role, 'owner', :checked => (@user.role == 'owner' ? true : false), class: "radio-inline" %>
  <%= label :role, 'owner' %>
    <br>
  <%= f.radio_button :role, 'manager', :checked => (@user.role == 'manager' ? true : false), class: "radio-inline" %>
  <%= label :role, 'manager' %>
    <br>
  <%= f.radio_button :role, 'employee',:checked => (@user.role == 'employee' ? true : false), class: "radio-inline" %>
  <%= label :role, 'employee' %>
  <% end %>

  </div>
<div class="actions col-md-6 pull-right">
  <%= f.submit "Update User", class: "btn btn-primary btn-md btn-block" %>
</div>
<% end %>

app/views/users/employees.html.erb
<h1> Employees </h1>
<hr>

<div class="pull-right">

  <% if can? :new, @user %>
    <%= link_to new_user_path  do %>
      <button class='btn btn-info btn-sm' role='button'>
        <i class='glyphicon glyphicon-plus'></i>
        ADD Employee
      </button>
    <% end %>
  <% end %>
</div>

<table class="table table-hover table-striped" id="datatable">
  <thead>
    <tr>
      <th>
        Name
      </th>
      <th>
        Email
      </th>
      <th style="width: 30px">
      </th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |user| %>
    <tr>
       <td class="text-capitalize">
         <%= "#{user.last_name}, #{user.first_name}" %>
       </td>
       <td>
         <a target="_blank"href="mailto:<%= user.email %>"><%= user.email %></a>
      </td>
      <td>
        <div class="dropdown text-center">
          <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button">

              <span aria-hidden="true" class="glyphicon glyphicon-wrench"></span>
              Options
              <span class="caret"></span>

          </button>
          <ul class="dropdown-menu">
            <li class="text-primary">
              <% if can? :add, Client %>
                <%= link_to employee_new_client_path(user) do %>
                  <i class='glyphicon glyphicon-plus text-primary'></i>
                  Add Client
                <% end %>
              <% end %>
            </li>
            <li class="text-info">
              <% if can? :show_employee, user %>
                <%= link_to show_employee_path(user) do %>
                  <i class='glyphicon glyphicon-briefcase text-info'></i>
                  Details
                <% end %>
              <% end %>
            </li>
            <li class="text-info">
              <% if can? :edit, user %>
                <%= link_to edit_user_path(user) do %>
                  <i class='glyphicon glyphicon-edit text-info'></i>
                  Edit Profile
                <% end %>
              <% end %>
            </li>
            <li class="text-warning">
                <% if can? :change_password, user %>
                  <%= link_to change_password_path(user) do %>
                  <i class='glyphicon glyphicon-remove text-warning'></i>
                  Change Password
                <% end %>
              <% end %>
            </li>
            <li class="text-danger">
              <% if can? :destroy, user %>
              <%= link_to user, method: :delete, data: {confirm: 'Are you sure?', verify: 'Delete', verify_text: 'Type "Delete" to confirm'} do %>
              <i class='glyphicon glyphicon-trash text-danger'></i>
              Delete
              <% end %>
              <% end %>
            </li>
          </ul>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/employees_report.html.erb
<h1>Employees#Reports</h1>
<p>Find me in app/views/users/employees_report.html.erb</p>

<table id="datatable" class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Employee Name</th>
      <th>Total Clients</th>
      <th>Total Sales</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td>
          <%= employee.name %>
        </td>
        <td>
          <%= employee.clients.size %>
        </td>
        <td>
          P <%= number_with_precision(employee.total_sales, :precision => 2, :delimiter => ',') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<h1> List of user types </h1>
<hr>
<ul>
  <li>
    <h4>
    <%= link_to employees_path do %>
      Employees
    <% end %>
    </h4>
  </li>
  <li>
    <h4>
    <%= link_to managers_path do %>
      Managers
    <% end %>
    </h4>
  </li>
  <li>
    <h4>
    <%= link_to owners_path do %>
      Owners
    <% end %>
    </h4>
  </li>
</ul>

app/views/users/managers.html.erb
<h1> Managers </h1>
<hr>

<div class="pull-right">
  <% if can? :new, @user %>
    <%= link_to new_user_path  do %>
      <button class='btn btn-info btn-sm' role='button'>
        <i class='glyphicon glyphicon-plus'></i>
        ADD Manager
      </button>
    <% end %>
  <% end %>
</div>

<table class="table table-hover table-striped" id="datatable">
  <thead>
    <tr>
      <th>
        Name
      </th>
      <th>
        Email
      </th>
      <th style="width: 30px">
      </th>
    </tr>
  </thead>
  <tbody>
    <% @managers.each do |user| %>
    <tr>
       <td class="text-capitalize">
         <%= "#{user.last_name}, #{user.first_name}" %>
       </td>
       <td>
         <%= user.email %>
      </td>
      <td>
        <div class="dropdown text-center">
          <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button">

              <span aria-hidden="true" class="glyphicon glyphicon-wrench"></span>
              Options
              <span class="caret"></span>

          </button>
          <ul class="dropdown-menu">
            <!-- <li class="text-primary">
              <% if can? :add, Client %>
                <%= link_to employee_new_client_path(user) do %>
                  <i class='glyphicon glyphicon-plus text-primary'></i>
                  Add Client
                <% end %>
              <% end %>
            </li> -->
            <li class="text-info">
              <% if can? :show_manager, user %>
                <%= link_to show_manager_path(user) do %>
                  <i class='glyphicon glyphicon-briefcase text-info'></i>
                  Details
                <% end %>
              <% end %>
            </li>
            <li class="text-info">
              <% if can? :edit, user %>
                <%= link_to edit_user_path(user) do %>
                  <i class='glyphicon glyphicon-edit text-info'></i>
                  Edit Profile
                <% end %>
              <% end %>
            </li>
            <li class="text-warning">
                <% if can? :change_password, user %>
                  <%= link_to change_password_path(user) do %>
                  <i class='glyphicon glyphicon-remove text-warning'></i>
                  Change Password
                <% end %>
              <% end %>
            </li>
            <li class="text-danger">
              <% if can? :destroy, user %>
              <%= link_to user, method: :delete, data: {confirm: 'Are you sure?', verify: 'Delete', verify_text: 'Type "Delete" to confirm'} do %>
              <i class='glyphicon glyphicon-trash text-danger'></i>
              Delete
              <% end %>
              <% end %>
            </li>
          </ul>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1> Add User </h1>
<hr>
<%= javascript_include_tag 'email_validation','data-turbolinks-track' =>true %>

<%= form_for @user, url: {action: 'create'}, builder: Judge::FormBuilder do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %>
    prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
  <div class="col-sm-5 col-md-8" id="panel">
    <div class="form-group">
      <%= f.label :email, class:"control-label", for:"inputEmail" %>
      <%= f.text_field :email, validate: true, type: "email", class: "form-control", required: "required", id:"inputEmail", placeholder: "sample@gmail.com, example@yahoo.com" %>
    </div>
    <div class="form-group">
      <%= f.label :password, class:"control-label", for:"inputPassword" %>
      <%= f.password_field :password, validate: true, class: "form-control", required: "required", id:"inputPassword" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, class:"control-label", for:"inputPassword" %>
      <%= f.password_field :password_confirmation, validate: true, class: "form-control", required: "required", id:"inputPassword" %>
    </div>
    <div class="form-group">
      <%= f.label :first_name, class:"control-label", for:"inputFirstName" %>
      <%= f.text_field :first_name, validate: true, class: "form-control", type: "text", required: "required", id:"inputFirstName", placeholder: "First Name goes here..."  %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, class:"control-label", for:"inputLastName" %>
      <%= f.text_field :last_name, validate: true, class: "form-control", type: "text", required: "required", id:"inputLastName", placeholder: "Last Name goes here..." %>
    </div>

    <h5>Role:</h5>
    <%= f.radio_button :role, 'owner'%>
    <%= label :role, 'owner' %>
    <br>
    <%= f.radio_button :role, 'manager' %>
    <%= label :role, 'manager' %>
    <br>
    <%= f.radio_button :role, 'employee' %>
    <%= label :role, 'employee' %>
  </div>
<div class="row">
  <hr>
  <div class="actions col-md-6 pull-right">
    <%= f.submit "Create User", class: "btn btn-primary btn-md btn-block" %>
  </div>
</div>
</div>
<% end %>

app/views/users/owners.html.erb
<h1> Owners </h1>
<hr>

<div class="pull-right">
  <% if can? :new, @user %>
    <%= link_to new_user_path  do %>
      <button class='btn btn-info btn-sm' role='button'>
        <i class='glyphicon glyphicon-plus'></i>
        ADD Owner
      </button>
    <% end %>
  <% end %>
</div>

<table class="table table-hover table-striped" id="datatable">
  <thead>
    <tr>
      <th>
        Name
      </th>
      <th>
        Email
      </th>
      <th style="width: 30px">
      </th>
    </tr>
  </thead>
  <tbody>
    <% @owners.each do |user| %>
    <tr>
       <td class="text-capitalize">
         <%= "#{user.last_name}, #{user.first_name}" %>
       </td>
       <td>
         <%= user.email %>
      </td>
      <td>
        <div class="dropdown text-center">
          <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button">

              <span aria-hidden="true" class="glyphicon glyphicon-wrench"></span>
              Options
              <span class="caret"></span>

          </button>
          <ul class="dropdown-menu">
            <!-- <li class="text-primary">
              <% if can? :add, Client %>
                <%= link_to employee_new_client_path(user) do %>
                  <i class='glyphicon glyphicon-plus text-primary'></i>
                  Add Client
                <% end %>
              <% end %>
            </li> -->
            <li class="text-info">
              <% if can? :show_owner, user %>
                <%= link_to show_owner_path(user) do %>
                  <i class='glyphicon glyphicon-briefcase text-info'></i>
                  Details
                <% end %>
              <% end %>
            </li>
            <li class="text-info">
              <% if can? :edit, user %>
                <%= link_to edit_user_path(user) do %>
                  <i class='glyphicon glyphicon-edit text-info'></i>
                  Edit Profile
                <% end %>
              <% end %>
            </li>
            <li class="text-warning">
                <% if can? :change_password, user %>
                  <%= link_to change_password_path(user) do %>
                  <i class='glyphicon glyphicon-remove text-warning'></i>
                  Change Password
                <% end %>
              <% end %>
            </li>
            <li class="text-danger">
              <% if can? :destroy, user %>
              <%= link_to user, method: :delete, data: {confirm: 'Are you sure?', verify: 'Delete', verify_text: 'Type "Delete" to confirm'} do %>
              <i class='glyphicon glyphicon-trash text-danger'></i>
              Delete
              <% end %>
              <% end %>
            </li>
          </ul>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show_employee.html.erb
<h1 class="text-capitalize"><%= "#{@employee.last_name}, #{@employee.first_name}" %></h1>

<div class="pull-right">
  <% if can? :edit, @user %>
  <%= link_to edit_user_path(@user) do %>
  <button class='btn btn-primary btn-sm' role='button'>
    <i class='glyphicon glyphicon-edit'></i>
    Edit Profile
  </button>
  <% end %>
  <% end %>

  <% if can? :change_password, @user %>
  <%= link_to change_password_path(@user) do %>
  <button class='btn btn-warning btn-sm' role='button'>
    <i class='glyphicon glyphicon-remove'></i>
    Change Password
  </button>
  <% end %>
  <% end %>
</div>
<hr>

<h3><%= @employee.email %></h3>
<hr>

<h2>Clients</h2>
<hr>

<div>
  <table class="table table-hover table-striped" id="clientdatatable">
    <thead>
      <tr>
        <th>Company Name</th>
        <th>Owner</th>
        <th>No. Of Transactions</th>
        <th>Status</th>
        <th style="width: 30px"></th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
      <tr>
        <td class="text-capitalize">
          <%= client.company_name %>
        </td>
        <td class="text-capitalize">
          <%= client.owner %>
        </td>
        <td>
            <%= client.transaction_count %>
        </td>
        <td>
          <%= client.status %>
        </td>
        <td>
          <%= link_to show_through_employee_path(@employee.id, client.id) do %>
          <button class='btn btn-info btn-sm' role='button'>
            <i class='glyphicon glyphicon-edit'></i>
            View Profile
          </button>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/users/show_manager.html.erb
<h1 class="text-capitalize"><%= "#{@manager.last_name}, #{@manager.first_name}" %></h1>

<div class="pull-right">
  <% if can? :edit, @user %>
  <%= link_to edit_user_path(@user) do %>
  <button class='btn btn-primary btn-sm' role='button'>
    <i class='glyphicon glyphicon-edit'></i>
    Edit Profile
  </button>
  <% end %>
  <% end %>

  <% if can? :change_password, @user %>
  <%= link_to change_password_path(@user) do %>
  <button class='btn btn-warning btn-sm' role='button'>
    <i class='glyphicon glyphicon-remove'></i>
    Change Password
  </button>
  <% end %>
  <% end %>
</div>
<hr>

<h3><%= @manager.email %></h3>
<hr>
<hr>

app/views/users/show_owner.html.erb
<h1 class="text-capitalize"><%= "#{@owner.last_name}, #{@owner.first_name}" %></h1>

<div class="pull-right">
  <% if can? :edit, @user %>
  <%= link_to edit_user_path(@user) do %>
  <button class='btn btn-primary btn-sm' role='button'>
    <i class='glyphicon glyphicon-edit'></i>
    Edit Profile
  </button>
  <% end %>
  <% end %>

  <% if can? :change_password, @user %>
  <%= link_to change_password_path(@user) do %>
  <button class='btn btn-warning btn-sm' role='button'>
    <i class='glyphicon glyphicon-remove'></i>
    Change Password
  </button>
  <% end %>
  <% end %>
</div>
<hr>

<h3><%= @owner.email %></h3>
<hr>
<hr>

app/views/users/view.html.erb
<h1>Users#view</h1>
<p>Find me in app/views/users/view.html.erb</p>