config/routes.rb
Rails.application.routes.draw do
  mount Judge::Engine => '/judge'

  get 'home' => 'home#index', as: 'home'

  # employee
  get 'employees' => 'users#employees', as: 'employees'
  get 'employees/:id' => 'users#show_employee', as: 'show_employee'

  #managers
  get 'managers' => 'users#managers', as: 'managers'
  get 'managers/:id' => 'users#show_manager', as: 'show_manager'


  #owners
  get 'owners' => 'users#owners', as: 'owners'
  get 'owners/:id' => 'users#show_owner', as: 'show_owner'


  # employee options
  get 'employees/:employee_id/new_client' => 'clients#new', as: 'employee_new_client'
  get 'employees/:employee_id/client/:id' => 'clients#show', as: 'show_through_employee'

  # root 'users#index'

  # logging and logging out
  root 'sessions#new'
  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create', as: 'check_login'
  get 'logout' => 'sessions#destroy', as: 'logout'

  # the various users
  resources :users

  # clients and their transactions
  resources :clients do
    resources :transactions do
      post 'pay' => 'transactions#pay', as: 'pay'
    end
  end

  # password_related
  get 'users/:id/change_password' => 'users#change_password', as: 'change_password'
  patch 'users/:id/change_password' => 'users#update_password'
  put 'users/:id/change_password' => 'users#update_password'

  post ':id/fees/new' => 'fees#create', as:'new_fee'

  get 'reports/services_report' => 'reports#services_report', as: "reports_services_report"

  get 'clients/:id/transactions/:transaction_id/edit/:provisional_receipts_id' => 'transactions#edit_for_modal', as: "edit_modal_provisional_receipts"
  patch 'clients/:id/transactions/:transaction_id/edit/:provisional_receipt_id' => 'provisional_receipts#update', as: "edit_provisional_receipts"

  get 'reports/accounts_receivable'

  get 'reports/employees_report'

  get 'reports/transactions_report'

  resources :reports

  resources :transactions, except: :new

  resources :fees

  resources :services

  resources :provisional_receipts, except: [:new, :create]
end

app/views/shared/_error_messages.html.erb
<div id="error_explanation">
  <h2><%= pluralize(form_model.errors.count, "error") %> prohibited this user from being saved:</h2>
  <ul>
    <% form_model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <hr class="alert-primary">
    <p class="pull-right"><a href="#" class="text-muted"><span class="glyphicon glyphicon-chevron-up"
                                                               aria-hidden="true"></span> Back to top</a></p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar
  <% if can? :manage, :all %>
      navbar-default
  <% else %>
      navbar-inverse
  <% end %>
   navbar-fixed-top" role="navigation">

  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle" data-target="#myNavbar" data-toggle="collapse" type="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home">
        <i class="custom-imgt_logo"></i>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <!-- gretel goes here -->
      <ul class="nav navbar-nav">
        <li>
          <ol class="breadcrumb">
            <%= render_breadcrumbs :tag => :li, :separator => "" %>
          </ol>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li class="dropdown">
          <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" id="user-dropdown" role="button">
            <%= current_user ? "Logged in as #{current_user.name}" : "" %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to edit_user_path(current_user) do %>
              <i class='glyphicon glyphicon-edit'></i>
              Edit Profile
              <% end %>
            </li>
            <li>
              <%= link_to change_password_path(current_user) do %>
              <i class='glyphicon glyphicon-lock'></i>
              Change Password
              <% end %>
            </li>
            <li>
              <%= link_to logout_path do %>
              <i class='glyphicon glyphicon-log-out'></i>
              Log-out
              <% end %>
            </li>
          </ul>
        </li>
        <% else %>
        <li>
          <%= link_to login_path do %>
          <i class='glyphicon glyphicon-log-in'></i>
          Log-in
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar-offcanvas" id="sidebar" role="navigation">

  <div id="SideMenu">
    <%= side_bar do %>

    <li id="homenav">
      <%= link_to home_path do %>
        <i class='glyphicon glyphicon-home'></i> Home
      <% end %>
    </li>

    <% if can? :manage, User %>
    <li id="employeesnav">
      <%= link_to users_path do %>
        <i class='glyphicon glyphicon-user'></i> Users
      <% end %>
    </li>
    <div class="sublinks collapse" id="employees">
      <%= side_child_link raw("<i class='glyphicon glyphicon-chevron-right'></i> Employees"), employees_path  %>
      <%= side_child_link raw("<i class='glyphicon glyphicon-chevron-right'></i> Managers"), managers_path  %>
      <%= side_child_link raw("<i class='glyphicon glyphicon-chevron-right'></i> Owners"), owners_path  %>
      <%= side_child_link raw("<i class='glyphicon glyphicon-plus'></i> Add"), new_user_path %>
    </div>
    <% end %>

    <li id="clientsnav">
      <%= link_to clients_path do %>
        <i class='glyphicon glyphicon-briefcase'></i> Clients
      <% end %>
    </li>

    <div class="sublinks collapse" id="clients">
      <%= side_child_link raw("<i class='glyphicon glyphicon-chevron-right'></i> Index"), clients_path %>
      <% if can? :create, Client %>
      <%= side_child_link raw("<i class='glyphicon glyphicon-plus'></i> Add"), new_client_path %>
      <% end %>
    </div>

    <li id="transactionsnav">
      <%= link_to transactions_path do %>
        <i class='glyphicon glyphicon-book'></i> Transactions
      <% end %>
    </li>

    <div class="sublinks collapse" id="transactions">
      <%= side_child_link raw("<i class='glyphicon glyphicon-chevron-right'></i> Index"), transactions_path %>
    </div>

    <% if can? :manage, Service %>
    <li id="servicesnav">
      <%= link_to services_path do %>
        <i class='glyphicon glyphicon-list-alt'></i> Services
      <% end %>
    </li>

    <div class="sublinks collapse" id="services">
      <%= side_child_link raw("<i class='glyphicon glyphicon-chevron-right'></i> Index"), services_path %>
      <%= side_child_link raw("<i class='glyphicon glyphicon-plus'></i> Add"), new_service_path %>
    </div>
    <% end %>

    <li id="reportsnav">
      <%= link_to reports_path do %>
        <i class='glyphicon glyphicon-folder-open'></i> Reports
      <% end %>
    </li>
    <div class="sublinks collapse" id="reports">
      <%= side_child_link raw("<i class='glyphicon glyphicon-chevron-right'></i> Accounts Receivable"), reports_accounts_receivable_path %>
      <%= side_child_link raw("<i class='glyphicon glyphicon-chevron-right'></i> Employees"), reports_employees_report_path %>
      <%= side_child_link raw("<i class='glyphicon glyphicon-chevron-right'></i> Transactions"), reports_transactions_report_path %>
      <%= side_child_link raw("<i class='glyphicon glyphicon-chevron-right'></i> Services"), reports_services_report_path %>
    </div>

    <% end %>
  </div>


</div>