config/routes.rb
Rails.application.routes.draw do
  mount Judge::Engine => '/judge'

  get 'home' => 'home#index', as: 'home'

  # employee
  get 'employees' => 'users#employees', as: 'employees'
  get 'employees/:id' => 'users#show_employee', as: 'show_employee'

  #managers
  get 'managers' => 'users#managers', as: 'managers'
  get 'managers/:id' => 'users#show_manager', as: 'show_manager'


  #owners
  get 'owners' => 'users#owners', as: 'owners'
  get 'owners/:id' => 'users#show_owner', as: 'show_owner'


  # employee options
  get 'employees/:employee_id/new_client' => 'clients#new', as: 'employee_new_client'
  get 'employees/:employee_id/client/:id' => 'clients#show', as: 'show_through_employee'

  # root 'users#index'

  # logging and logging out
  root 'sessions#new'
  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create', as: 'check_login'
  get 'logout' => 'sessions#destroy', as: 'logout'

  # the various users
  resources :users

  # clients and their transactions
  resources :clients do
    resources :transactions do
      post 'pay' => 'transactions#pay', as: 'pay'
    end
  end

  # password_related
  get 'users/:id/change_password' => 'users#change_password', as: 'change_password'
  patch 'users/:id/change_password' => 'users#update_password'
  put 'users/:id/change_password' => 'users#update_password'

  post ':id/fees/new' => 'fees#create', as:'new_fee'

  get 'reports/services_report' => 'reports#services_report', as: "reports_services_report"

  get 'clients/:id/transactions/:transaction_id/edit/:provisional_receipts_id' => 'transactions#edit_for_modal', as: "edit_modal_provisional_receipts"
  patch 'clients/:id/transactions/:transaction_id/edit/:provisional_receipt_id' => 'provisional_receipts#update', as: "edit_provisional_receipts"

  get 'reports/accounts_receivable'

  get 'reports/employees_report'

  get 'reports/transactions_report'

  resources :reports

  resources :transactions, except: :new

  resources :fees

  resources :services

  resources :provisional_receipts, except: [:new, :create]
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  has_many :transactions, :dependent => :restrict_with_error
  has_many :other_processing_fees, through: :transactions, class_name: "Service"
  validates :email, :allow_blank => true,:uniqueness => { :case_sensitive => false }, email: true
  validates :company_name, presence: true
  validates :owner, presence: true
  validates :address, presence: true
  validates :tel_num, presence: true
  validates :tin_num, presence: true, tin_num: true

  def self.search(query)
    where('company_name like ?', "%#{query}%")
  end

  def user_email
    user.email
  end

  def total_balance_of_transaction
    transactions.inject(0) {|sum, transaction| sum + transaction.total_balance}
  end

  def user_name
    user.name
  end

  def filtered_total_balance_of_transaction(startdate, enddate)
    transactions.filtered_pending_transactions(startdate, enddate).inject(0) { |sum, transaction| sum + transaction.total_balance}
  end

  def transaction_count
    transactions.size
  end

  def services
    hash_result = {}

    transactions.each do |transaction|
      transaction.service_names.each do |service|
        if hash_result[service]
          hash_result[service] += 1
        else
          hash_result[service] = 1
        end
      end
    end


    hash_result
  end

  def filtered_services(startdate, enddate)
    hash_result = {}

    transactions.each do |transaction|
      transaction.filtered_service_names(startdate, enddate).each do |service|
        if hash_result[service]
          hash_result[service] += 1
        else
          hash_result[service] = 1
        end
      end
    end

    hash_result
  end


end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :find_client, only: [:show, :edit, :destroy, :update, :show_through_employee]
  after_filter 'save_my_previous_url', only: [:new]
  load_and_authorize_resource
  add_breadcrumb "Home", :root_path

  def index
    add_breadcrumb "Clients List", clients_path
  end

  def show
    if params[:employee_id]
      @employee = User.find(params[:employee_id])
      add_breadcrumb "Employees", employees_path
      add_breadcrumb @employee.email, show_employee_path(params[:employee_id])
    else
      add_breadcrumb "Clients List", clients_path
    end
    add_breadcrumb @client.company_name
    @transactions = @client.transactions
    @transaction = Transaction.new
  end

  def new
    @employees = get_employees
    puts "************************"
    puts @employees
    puts "************************"
    puts "************************"
    @client = Client.new

    if params[:employee_id]
      @employee = User.find(params[:employee_id])
      add_breadcrumb "Employees", employees_path
      add_breadcrumb @employee.email, show_employee_path(params[:employee_id])
      @client.user_id = params[:employee_id]
      @withparams = true
    else
      add_breadcrumb "Clients List", clients_path
    end

    add_breadcrumb "New Client"
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:success] = 'Client successfully added.'
      redirect_to client_path(@client)
    else
      flash[:notice] = 'Client WAS NOT added.'
      render :new
    end
  end

  def edit
    add_breadcrumb "Clients Lists", clients_path
    add_breadcrumb "Edit " + @client.company_name , edit_client_path
    @employees = get_employees
  end

  def destroy
    @client.destroy

    if @client.destroyed?
      flash[:success] = 'Client successfully deleted.'
    else
      flash[:error] = 'Client WAS NOT deleted. This client may still have transactions.'
    end
    redirect_to clients_path
  end

  def update
    add_breadcrumb "Clients List", clients_path
    add_breadcrumb "Edit Client" + @client.company_name, edit_client_path
    if @client.update(client_params)
      flash[:success] = 'Client successfully updated.'
      redirect_to client_path(@client)
    else
      flash[:error] = 'Client WAS NOT edited.'
      render :edit
    end
  end

  def assign
    add_breadcrumb "Clients Lists", clients_path
    add_breadcrumb @client.company_name , clients_assign_path
  end

  private

  def client_params
    params.require(:client).permit(:company_name, :owner, :representative, :address, :tel_num, :email, :tin_num, :status, :user_id)
  end

  def find_client
    @client = Client.find(params[:id])
  end

  def save_my_previous_url
    session[:my_previous_url] = URI(request.referer || '').path
  end
end

app/views/clients/_client_details.html.erb
<h1 class="text-capitalize"> <%= @client.company_name %> </h1>

<hr>

<div class="pull-right">
  <%= link_to edit_client_path(@client.id) do %>
    <button class='btn btn-primary btn-sm' role='button'>
      <i class='glyphicon glyphicon-edit'></i> Edit Profile
    </button>
  <% end %>
</div>


<table class="table table-hover table-striped">
<tbody>

    <tr>
      <th>Owner</th>
      <th> <%= @client.owner %></th>
    </tr>
    <tr>
      <th>Representative</th>
      <th> <%= @client.representative %></th>
    </tr>
    <tr>
      <th>Address</th>
      <th> <%= @client.address %> </th>
    </tr>
    <tr>
      <th>Telephone Number</th>
      <th> <%= @client.tel_num %> </th>
    </tr>
    <tr>
      <th>Email Address</th>
      <th> <%= @client.email  %></th>
    </tr>
    <tr>
      <th>Tin Number</th>
      <th> <%= @client.tin_num %></th>
    </tr>
    <tr>
      <th>Employee-in-charge</th>
      <th> <%= @client.user_name %></th>
    </tr>
  </tbody>

</table>
</hr>
<h1 class="text-capitalize"> Transactions</h1>


<div class="pull-right">
  <%= link_to new_client_transaction_path(@client.id) do %>
   <button class='btn btn-info btn-sm' role='button'>
     <i class='glyphicon glyphicon-briefcase'></i> Add Transaction
   </button>
  <% end %>
</div>


<div>
  <table id="clientdatatable" class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Billing Number</th>
        <th>Total Amount</th>
        <th>Status</th>
        <th style="width: 30px">
        </th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
      <tr>
        <td class="text-capitalize">
          # <%= "#{transaction.billing_num}" %>
        </td>
        <td>
          Php <%= number_with_precision(transaction.total_balance, :precision => 2, :delimiter => ',') %>
        </td>
        <td>
          <% if transaction.pending? %>
            <button type="button" class="btn btn-danger">
              Pending - Php <%= number_with_precision(transaction.remaining_balance, :precision => 2, :delimeter => ',') %>
            </button>
          <% else %>
            <button type="button" class="btn btn-success">Paid</button>
          <% end %>
        </td>
        <td>
          <div class="dropdown">
            <button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button">
              Options
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li class="text-info">
                  <%= link_to transaction do %>
                  <i class='glyphicon glyphicon-briefcase text-info'></i> Details
                  <% end %>
              </li>
            </ul>
          </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/clients/_form.html.erb
<%= javascript_include_tag 'email_validation','data-turbolinks-track' =>true %>

<%= form_for form_model, url: {action: action}, builder: Judge::FormBuilder do |f| %>
    <div class="row">
  <div class="col-sm-5 col-md-8" id="panel">
  <% if form_model.errors.any? %>
    <%= render partial: "shared/error_messages", locals: {form_model: form_model} %>
  <% end %>

  <div class="form-group">
    <%= f.label :company_name, class:"control-label", for:"inputCompanyName" %>
    <%= f.text_field :company_name, validate: true, class: "form-control", required: "required", id:"inputCompanyName", placeholder: "Insert Company Name here..." %>
  </div>

  <div class="form-group">
    <%= f.label :owner, class:"control-label", for:"inputOwner" %>
    <%= f.text_field :owner, validate: true, class: "form-control", required: "required", id:"inputOwner", placeholder: "Insert Owner of Company here..." %>
  </div>

  <div class="form-group">
    <%= f.label :representative, class:"control-label", for:"inputRepresentative" %>
    <%= f.text_field :representative, validate: true, class: "form-control", id:"inputRepresentative", placeholder: "Insert Representative of Company here..."  %>
  </div>

  <div class="form-group">
    <%= f.label :address, class:"control-label", for:"inputAddress" %>
    <%= f.text_field :address, validate: true,  class: "form-control", size:"150", required: "required", id:"inputAddress"%>

  </div>

  <div class="form-group">
    <%= f.label :tel_num, class:"control-label", for:"inputTelNum" %>
    <%= f.text_field :tel_num, validate: true, class: "form-control", required: "required", id:"inputTelNum", placeholder: "Insert Telephone Number of Company here..." %>
  </div>

  <div class="form-group">
    <%= f.label :email, class:"control-label", for:"inputClientEmail" %>
    <%= f.text_field :email, validate: true, class: "form-control", id:"inputClientEmail", placeholder: "Insert Email of Company here..." %>
  </div>

  <div class="form-group">
    <%= f.label :tin_num, class:"control-label", for:"inputTinNum" %>
    <%= f.text_field :tin_num, validate: true, class: "form-control", required: "required", id:"inputTinNum", placeholder: "Insert Tin Number of Company here..." %>
  </div>

  <h5>Status:</h5>
    <%= f.radio_button :status, 'Active', :checked => true, class: "radio-inline" %>
    <%= label :role, 'active' %>
      <br>
    <%= f.radio_button :status, 'Inactive', class: "radio-inline" %>
    <%= label :role, 'inactive' %>
<br>
  <div class="form-group">
    <% if @withparams %>
      <%= f.hidden_field :user_id, class: "form-control"%>
    <% else %>
        <%= f.label :user_id, 'Assigned to: ', class:"control-label", for:"inputEmployee" %>
        <%= f.select :user_id, @employees.collect {|employee| ["#{employee.last_name}, #{employee.first_name}", employee.id]}, {},  { class: 'form-control', disabled: @withparams } %>
    <% end %>
  </div>
</div>
  <div class="row">
    <hr>
  <div class="actions col-md-6 pull-right">
    <%= f.submit action.capitalize + " Client", class: "btn btn-primary btn-md btn-block" %>
  </div>
</div>
</div>
<% end %>

<script>
$("#inputTinNum").mask("999-999-999-999",{placeholder:"xxx-xxx-xxx-xxx"});
</script>

app/views/clients/edit.html.erb
<h1> Edit Client </h1>
<hr>
<%= render partial: 'form', locals: {form_model: @client, action: 'update'} %>

app/views/clients/index.html.erb
<h1> Clients</h1>
<hr>


<div class="pull-right">
  <% if can? :new, @client %>
  <%= link_to new_client_path  do %>
  <button class='btn btn-info btn-sm' role='button'>
    <i class='glyphicon glyphicon-plus'></i>
    ADD Client
  </button>
  <% end %>
  <% end %>
</div>

<table id="clientdatatable" class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Company Name</th>
      <th>Employee In-charge</th>
      <th>Status</th>
      <th style="width: 30px">
      </th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
    <tr>
      <td class="text-capitalize">
        <%= link_to client_path(client) do %>
          <%= "#{client.company_name}" %>
        <% end %>
      </td>
      <td>
        <% if client.user %>
          <%= client.user_name %>
        <% else  %>
          <span>Not assigned</span>
        <% end %>
      </td>
      <td>
        <%= client.status %>
      </td>
      <td>
        <div class="dropdown">
          <button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button">
            Options
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li class="text-primary">
                <%= link_to new_client_transaction_path(client) do %>
                <i class='glyphicon glyphicon-plus text-primary'></i> New Transaction
                <% end %>
            </li>
            <li class="text-info">
                <%= link_to client_path(client) do %>
                <i class='glyphicon glyphicon-briefcase text-info'></i> Details
                <% end %>
            </li>
            <li class="text-info">
                <%= link_to edit_client_path(client) do %>
                <i class='glyphicon glyphicon-edit text-info'></i> Edit Profile
                <% end %>
            </li>
            <li class="text-danger">
              <% if can? :destroy, client %>
                <%= link_to client, method: :delete, data: {confirm: 'Do you want to delete this client?', verify: 'Delete', verify_text: 'Type "Delete" to confirm'} do %>
                  <i class='glyphicon glyphicon-trash text-danger'></i>
                  Delete
                <% end %>
              <% end %>
            </li>
          </ul>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<h1> New Client<%= " for #{@employee.name}" if @employee %> </h1>
<hr>
<%= render partial: 'form', locals: {form_model: @client, action: 'create'} %>

app/views/clients/show.html.erb
  <%= render "clients/client_details" %>

app/views/clients/show_through_employee.html.erb
  <%= render "clients/client_details" %>