config/routes.rb
Rails.application.routes.draw do
  mount Judge::Engine => '/judge'

  get 'home' => 'home#index', as: 'home'

  # employee
  get 'employees' => 'users#employees', as: 'employees'
  get 'employees/:id' => 'users#show_employee', as: 'show_employee'

  #managers
  get 'managers' => 'users#managers', as: 'managers'
  get 'managers/:id' => 'users#show_manager', as: 'show_manager'


  #owners
  get 'owners' => 'users#owners', as: 'owners'
  get 'owners/:id' => 'users#show_owner', as: 'show_owner'


  # employee options
  get 'employees/:employee_id/new_client' => 'clients#new', as: 'employee_new_client'
  get 'employees/:employee_id/client/:id' => 'clients#show', as: 'show_through_employee'

  # root 'users#index'

  # logging and logging out
  root 'sessions#new'
  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create', as: 'check_login'
  get 'logout' => 'sessions#destroy', as: 'logout'

  # the various users
  resources :users

  # clients and their transactions
  resources :clients do
    resources :transactions do
      post 'pay' => 'transactions#pay', as: 'pay'
    end
  end

  # password_related
  get 'users/:id/change_password' => 'users#change_password', as: 'change_password'
  patch 'users/:id/change_password' => 'users#update_password'
  put 'users/:id/change_password' => 'users#update_password'

  post ':id/fees/new' => 'fees#create', as:'new_fee'

  get 'reports/services_report' => 'reports#services_report', as: "reports_services_report"

  get 'clients/:id/transactions/:transaction_id/edit/:provisional_receipts_id' => 'transactions#edit_for_modal', as: "edit_modal_provisional_receipts"
  patch 'clients/:id/transactions/:transaction_id/edit/:provisional_receipt_id' => 'provisional_receipts#update', as: "edit_provisional_receipts"

  get 'reports/accounts_receivable'

  get 'reports/employees_report'

  get 'reports/transactions_report'

  resources :reports

  resources :transactions, except: :new

  resources :fees

  resources :services

  resources :provisional_receipts, except: [:new, :create]
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  load_and_authorize_resource
  after_filter 'save_my_previous_url', only: [:new]
  add_breadcrumb "Home", :root_path

  def index
    user = User.find current_user
    if user.role == 'employee'
      @transactions = user.transactions
    else
      @transactions = Transaction.all
    end
    add_breadcrumb "Transactions List", transactions_path
  end

  def show
    @transaction = Transaction.find(params[:id])
    @payments = get_payments(@transaction.id)
    @client = Client.find(@transaction.client_id)
    @provisional_receipt = ProvisionalReceipt.new

    add_breadcrumb "Clients List", clients_path
    add_breadcrumb @client.company_name, client_path(@client.id)
    add_breadcrumb "Transaction No. #{@transaction.billing_num}"
  end

  def new
    @transaction = Transaction.new
    @transaction.client = Client.find(params[:client_id])
    @client = @transaction.client

    @transaction.other_processing_fees.build
    @services = get_services

    add_breadcrumb "Clients List", clients_path
    add_breadcrumb @client.company_name, client_path(@client.id)
    add_breadcrumb "New Transaction"
    @last_transaction = Transaction.last
    if @last_transaction == nil
      @transaction.billing_num = '00001'
    else
      @transaction.billing_num = @last_transaction.billing_num.succ
    end
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @client = Client.find(@transaction.client_id)

    unless @transaction.save
      @services = get_services
      render :new
      return
    end

    if params[:selectize]
      params[:selectize].each do |value|
        @transaction.other_processing_fees << Service.find(value).make
      end
    end

    add_breadcrumb "Transactions List", transactions_path
    redirect_to client_path(@client.id)
  end

  def new_payment
    @pr = ProvisionalReceipt.new(provisional_receipt_params)
    @transaction = Transaction.find(@pr.transaction_id)

    if @pr.amount_paid > @transaction.remaining_balance
      raise 'Amount paid is greater than the remaining balance'
    else
      @transaction.pay(@pr.receipt_no,@pr.amount_paid, @pr.note)
    end

    redirect_to transaction_path(@transaction.client_id,@transaction.id)
  end

  def edit
    @services = get_services
    services_id = {}
    @services.each do |service|
        services_id[service.complete_name] = service.id
    end

    @transaction = Transaction.find params[:id]
    @selected_services = @transaction.other_processing_fees.collect { |x| services_id[x.complete_name] }
    @client = @transaction.client

    add_breadcrumb "Clients List", clients_path
    add_breadcrumb @client.company_name, client_path(@client.id)
    add_breadcrumb "Edit Transaction No. #{@transaction.billing_num}"
  end

  def edit_for_modal
    @provisional_receipt = ProvisionalReceipt.find params[:provisional_receipts_id]
    render :partial=>'edit_modal'
  end

  def update
    @transaction = Transaction.find params[:id]

    if @transaction.update_info transaction_params
      @transaction.other_processing_fees.each { |x| x.destroy }
      if params[:selectize]
        params[:selectize].each do |value|
          @transaction.other_processing_fees << Service.find(value).make
        end
      end

      flash[:success] = 'Transaction successfully updated.'
      redirect_to(@transaction)
    else
      @services = get_services
      services_id = {}
      @services.each do |service|
          services_id[service.complete_name] = service.id
      end
      @selected_services = @transaction.other_processing_fees.collect { |x| services_id[x.complete_name] }
      @client = @transaction.client

      add_breadcrumb "Clients List", clients_path
      add_breadcrumb @client.company_name, client_path(@client.id)
      add_breadcrumb "Edit Transaction No. #{@transaction.billing_num}"

      flash[:error] = 'Transaction WAS NOT updated.'
      render :edit
    end
  end

  def pay
    @transaction = Transaction.find params[:transaction_id]

    a = payment_params
    @transaction.pay a[:receipt_no], a[:amount_paid], a[:note]

    redirect_to @transaction
  end

  def destroy
    @transaction = Transaction.find params[:id]
    @transaction.destroy

    if @transaction.destroyed?
      flash[:success] = 'Transaction successfully deleted.'
    else
      flash[:error] = 'Transaction WAS NOT deleted. This transaction may still have payments.'
    end

    redirect_to transactions_path
  end

  private

  def payment_params
    params.require(:provisional_receipt).permit(:receipt_no,
                                                :amount_paid,
                                                :note)
  end

  def transaction_params
    params.require(:transaction).permit(:billing_num,
                                        :retainers_fee,
                                        :vat,
                                        :percentage,
                                        :withholding_1601c,
                                        :withholding_1601e,
                                        :employee_benefit_sss,
                                        :employee_benefit_philhealth,
                                        :employee_benefit_pag_ibig,
                                        :discount,
                                        :client_id)
  end

  def save_my_previous_url
    session[:my_previous_url] = URI(request.referer || '').path
  end
end

app/views/transactions/_form.html.erb
<%= javascript_include_tag 'judge_validation','data-turbolinks-track' =>true %>
<%= form_for form_model, url: {action: action}, builder: Judge::FormBuilder do |f| %>
<% if form_model.errors.any? %>
<%= render partial: "shared/error_messages", locals: {form_model: form_model} %>
<% end %>
<div class="col-sm-5 col-md-8" id="panel">
  <div class="form-group">
    <%= f.label :billing_num, class:"control-label", for:"inputBillingNumber" %>
    <%= f.text_field :billing_num, validate: true, class: "form-control", type: "number", required: "required", id:"inputBillingNumber", placeholder: "Insert Billing Number here...", readonly: "true" %>
  </div>

  <div class="form-group">
    <%= f.label :retainers_fee, class:"control-label", for:"inputRetainersFee" %>
    <%= f.text_field :retainers_fee, validate: true, class: "form-control", type:"number", id:"inputRetainersFee", placeholder: "Insert Retainers Fee here..." %>
  </div>

  <div class="form-group">
    <%= f.label :vat, class:"control-label", for:"inputVat" %>
    <%= f.text_field :vat, validate: true, class: "form-control", type: "number", id:"inputVat", placeholder:"Insert VAT here..."  %>
  </div>

  <div class="form-group">
    <%= f.label :percentage, class:"control-label", for:"inputPercentage" %>
    <%= f.text_field :percentage, validate: true, class: "form-control", type: "number", id:"inputPercentage", placeholder:"Insert Percentage here..."%>
  </div>

  <div class="form-group">
    <%= f.label :withholding_1601c, class:"control-label", for:"inputWithHolding1601c" %>
    <%= f.text_field :withholding_1601c, validate: true, class: "form-control", type: "number", id:"inputWithHolding1601c", placeholder: "Insert Withholding 1601c here..."  %>
  </div>

  <div class="form-group">
    <%= f.label :withholding_1601e, class:"control-label", for:"inputWithHolding1601e" %>
    <%= f.text_field :withholding_1601e, validate: true, class: "form-control", type: "number",   id:"inputWithHolding1601e", placeholder: "Insert Withholding 1601e here..."  %>
  </div>

  <div class="form-group">
    <%= f.label :employee_benefit_sss, class:"control-label", for:"inputEmployeeBenefitSSS" %>
    <%= f.text_field :employee_benefit_sss, validate: true, class: "form-control", type: "number",  id:"inputEmployeeBenefitSSS", placeholder: "Insert Employee Benefit SSS here..."  %>
  </div>

  <div class="form-group">
    <%= f.label :employee_benefit_philhealth, class:"control-label", for:"inputEmployeeBenefitPhilHealth" %>
    <%= f.text_field :employee_benefit_philhealth, validate: true, class: "form-control", type: "number",  id:"inputEmployeeBenefitPhilHealth", placeholder: "Insert Employee Benefit PhilHealth here..."  %>
  </div>

  <div class="form-group">
    <%= f.label :employee_benefit_pag_ibig, class:"control-label", for:"inputEmployeeBenefitPagibig" %>
    <%= f.text_field :employee_benefit_pag_ibig, validate: true, class: "form-control", type: "number",  id:"inputEmployeeBenefitPagibig", placeholder: "Insert Employee Benefit Pag ibig here..."  %>
  </div>

  <label>Services:
  </label>
  <div class="form-group">
    <%= select_tag "selectize", options_from_collection_for_select(@services, :id, :display, @selected_services), class:"form-control selectize input-lg", multiple: true, placeholder:"Click here to see list of available services..."%>
  </div>
  <div class="form-group">
    <%= f.label :discount, class:"control-label", for:"inputDiscount" %>
    <%= f.text_field :discount, validate: true, class: "form-control", type: "number",  id:"inputDiscount", placeholder: "Insert Discount in percent here..."  %>
  </div>

  <div class="form-group">
    <%= f.hidden_field :client_id, validate: true, class: "form-control" %>
  </div>
</div>

<div class="actions col-md-6 pull-right">
  <%= f.submit action.capitalize + " Transaction", class: "btn btn-primary btn-md btn-block" %>
</div>

<% end %>

<script>

  document.getElementById("inputVat").onblur = function () {
    if (this.value.length > 0) {
      $("#inputPercentage").prop("disabled", true);
    } else {
      $("#inputPercentage").prop("disabled", false);}
  };

  document.getElementById("inputPercentage").onblur = function () {
    if (this.value.length > 0) {
      $("#inputVat").prop("disabled", true);
    } else {
      $("#inputVat").prop("disabled", false);}
  };
</script>

app/views/transactions/_new_modal.html.erb
<!-- Modal -->
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-label="Close" class="close" data-dismiss="modal" type="button">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 class="modal-title" id="myModalLabel">Payment Form</h3>
        <hr>
        <div class="row">
          <div class="col-md-4">
            <h5>Billing Number:</h5>
          </div>
          <div class="col-md-8">
            <h5 class="pull-right">
              #<%= @transaction.billing_num%></h5>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <h5>Total:</h5>
          </div>
          <div class="col-md-8">
            <h5 class="pull-right">
              Php
              <%= @transaction.total_balance%></h5>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <h5>Remaining Balance:</h5>
          </div>
          <div class="col-md-8">
            <h5 class="pull-right">
              Php
              <%= @transaction.remaining_balance %></h5>
          </div>
        </div>
      </div>
      <%= render partial: 'paymentform', locals: {form_model: @provisional_receipt, a: client_transaction_pay_path(@transaction.client_id, @transaction.id)} %>


      <!-- end form for payments -->
    </div>

  </div>

app/views/transactions/_other_processing_fee_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :id, "Services: " %>
    <%= f.select :id, options_from_collection_for_select(@services, :id, :display), class: "form-control selectize input-lg", multiple: false, placeholder: "Click here to see list of available services..." %>
  </div>
  <div class="form-group">
    <%= f.label :discount, class:"control-label", for:"inputDiscount" %>
    <%= f.text_field :discount, validate: true, class: "form-control", id: "inputDiscount", type: "number", placeholder: "Insert Discount on this Service"%>
  </div>

  <%= link_to_remove_association "remove fee", f%>
</div>

app/views/transactions/_paymentform.html.erb
<%= form_for form_model, url: a, builder: Judge::FormBuilder do |f|  %>
  <div class="modal-body">

    <!-- form for payments -->

    <div class="form-group">
      <%= f.label :receipt_no, class:"control-label", for:"inputReceiptNumber" %>
      <%= f.text_field :receipt_no, class: "form-control", required: "required", id:"inputReceiptNumber", placeholder: "Insert Receipt number here..." %>
    </div>
    <div aria-label="..." class="btn-group pull-right" role="group">
      <button class="btn btn-default" onclick="payQuarter()" type="button">25%</button>
      <button class="btn btn-default" onclick="payHalf()" type="button">50%</button>
      <button class="btn btn-default" onclick="payFull()" type="button">Full</button>
    </div>
    <div class="form-group">
      <%= f.label :amount_paid, class:"control-label", for:"inputAmountPaid" %>
      <%= f.text_field :amount_paid, class: "form-control", required: "required", id:"inputAmountPaid", placeholder: "Insert Amount here..." %>
    </div>

    <div class="form-group">
      <%= f.label :note, class:"control-label", for:"inputNote" %>
      <%= f.text_field :note, class: "form-control", required: "required", id:"inputNote", placeholder: "Insert Note for payment here..." %>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn btn-danger" data-dismiss="modal" type="button">Close</button>
    <div class="actions col-md-6 pull-right">
      <%= f.submit "Submit", class: "btn btn-primary btn-md btn-block" %>
    </div>
  </div>
<% end %>

app/views/transactions/accounts_receivable.html.erb
<h1>Transactions#accounts_receivable</h1>
<p>Find me in app/views/transactions/accounts_receivable.html.erb</p>

<table id="transactions-datatable" class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Billing Number</th>
      <th>Client</th>
      <th>Remaining Balance</th>
      <th>Date Created</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td>
          <%= transaction.billing_num %>
        </td>
        <td>
          <% if transaction.client %>
            <%= transaction.client.company_name %>
          <% else %>
            <span>Deleted Client</span>
          <% end %>
        </td>
        <td>
          <%= transaction.remaining_balance %>
        </td>
        <td>
          <%= transaction.created_at.strftime("%d %b. %Y") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transactions/create.html.erb
<h1 class="text-capitalize">  Add Transaction </h1>
<hr>

app/views/transactions/destroy.html.erb
<h1 class="text-capitalize">  Delete Transaction</h1>
<hr>

app/views/transactions/edit.html.erb
<h1 class="text-capitalize">  Edit Transaction </h1>
<hr>

<%= render partial: 'form', locals: {form_model: @transaction, action: 'update'} %>

app/views/transactions/index.html.erb
<h1 class="text-capitalize">  Transactions </h1>
<hr>
<table class="table table-hover table-striped" id="transactions-datatable">
  <thead>
    <tr>
      <th>Billing Number</th>
      <th>Client Name</th>
      <th>Total Amount</th>
      <th>Remaining Balance</th>
      <th>Status</th>
      <th style="width: 30px"></th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
    <tr>
      <td class="text-capitalize">
        # <%= "#{transaction.billing_num}" %>
      </td>
      <td class="text-capitalize">
      <%= "#{transaction.client.company_name}" %>
    </td>
      <td>
        Php <%= transaction.total_balance %>
      </td>
      <td>
        Php <%= transaction.remaining_balance %></b>
        </td>
      <td>
        <% if transaction.pending? %>
          <button type="button" class="btn btn-danger">Pending</button>
        <% else %>
          <button type="button" class="btn btn-success">Paid</button>
        <% end %>
      </td>
      <td>
        <div class="dropdown">
          <button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button">
            Options
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li class="text-info">
                <%= link_to transaction do %>
                <i class='glyphicon glyphicon-briefcase text-info'></i> Details
                <% end %>
            </li>
          </ul>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
  </table>

app/views/transactions/new.html.erb
<h1 class="text-capitalize">  Add Transaction </h1>
<hr>
<%= render partial: 'form', locals: {form_model: @transaction, action: 'create'} %>

app/views/transactions/show.html.erb
    <h1>
      Transaction Details
    </h1>
    <hr>
    <table class="table table-hover table-striped">
      <h2>  <%= "#{@transaction.client.company_name}" %> </h2>
      <h3> Billing #: <%= "#{@transaction.billing_num}" %> </h3>

      <thead>
        <tr>
          <th>Name </th>
          <th>Price </th>
        </tr>
      </thead>
      <tbody>

        <% @transaction.get_fees.each do |name, value| %>
        <tr>
          <td><%= name %></td>
          <td>
            Php <%= value || 0 %>
          </td>

        </tr>
        <% end %>

        <tr>
          <td>
          <b>  <p class="pull-right">Total:</p></b>
          </td>
          <td><b>
              Php <%= number_with_precision(@transaction.total_balance, :precision => 2, :delimiter => ',') %>
          </td>

        </tr>
        <tr>
          <td>
          <b>  <p class="pull-right">  Remaining Balance:</p></b>
          </td>
          <td><b>
            Php <%= number_with_precision(@transaction.remaining_balance, :precision => 2, :delimiter => ',') %>
          </td>

        </tr>
    </table>

      <input type="button" data-target="#myModal" data-toggle="modal" id="paymentFormButton" type="button">
    </input>
  <br>
  <hr>

  <h1>Payment Log</h1>

  <table class="table table-hover table-striped" id="transactions-datatable">
    <thead>
      <tr>
        <th>Receipt No.</th>
        <th>Note</th>
        <th>Amount Paid</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @payments.each do |payment| %>
      <tr>
        <td class="text-capitalize">
          #
          <%= "#{payment.receipt_no}" %>
        </td>
        <td class="notes">
          <em><%= payment.note %></em>
        </td>
        <td>
          Php <%= number_with_precision(payment.amount_paid, :precision => 2, :delimiter => ',') %>
        </td>
        <td>
          <div class="dropdown">
            <button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button">
              Options
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <!-- <li class="text-info">
                  <%= link_to edit_provisional_receipts_path(@client.id, @transaction.id, payment.id) do %>
                  <i class='glyphicon glyphicon-briefcase text-info'></i> Edit Payment
                  <% end %>
              </li> -->
              <li class="text-danger">
                <% if can? :destroy, payment %>
                <%= link_to payment, method: :delete, data: {confirm: 'Are you sure?'} do %>
                <i class='glyphicon glyphicon-trash text-danger'></i>
                Delete
                <% end %>
                <% end %>
              </li>
            </ul>
          </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <!-- Modal -->
  <div aria-labelledby="myModalLabel" class="modal fade" id="myModal" role="dialog" tabindex="-1">
    <%= render "transactions/new_modal"%>
  </div>


</div>

<script>
window.onload = disableButton();
function disableButton() {
        if (<%= @transaction.pending? %> == true) {
          document.getElementById("paymentFormButton").value="Add Payment";
          document.getElementById("paymentFormButton").disabled = false;
          document.getElementById("paymentFormButton").setAttribute("class", "pull-right btn btn-lg btn-primary");
        } else if (<%= @transaction.pending? %>  == false) {
          document.getElementById("paymentFormButton").value="Fully Paid";
          document.getElementById("paymentFormButton").disabled = true;
          document.getElementById("paymentFormButton").setAttribute("class", "pull-right btn btn-lg btn-success");
        }
      }
  function payQuarter() {
    document.getElementById("inputAmountPaid").focus();
    document.getElementById("inputAmountPaid").value = <%= @transaction.remaining_balance %> / 4;
  }

  function payHalf() {
    document.getElementById("inputAmountPaid").focus();
    document.getElementById("inputAmountPaid").value = <%= @transaction.remaining_balance %> / 2;
  }

  function payFull() {
    document.getElementById("inputAmountPaid").focus();
    document.getElementById("inputAmountPaid").value = <%= @transaction.remaining_balance %>;
  }

</script>

app/views/transactions/update.html.erb
<h1 class="text-capitalize"> Edit Transaction  </h1>
<hr>